"""

Revision ID: 7b2687f5dc1e
Revises: 48e32df41eb8
Create Date: 2024-12-26 23:14:26.763351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2687f5dc1e'
down_revision: Union[str, None] = '48e32df41eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admissions', ['id'])
    op.create_unique_constraint(None, 'city', ['id'])
    op.create_unique_constraint(None, 'doctor_specialization', ['id'])
    op.create_unique_constraint(None, 'doctors', ['id'])
    op.create_unique_constraint(None, 'hospital', ['id'])
    op.create_unique_constraint(None, 'lab_tests', ['id'])
    op.create_unique_constraint(None, 'users_data', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_data', type_='unique')
    op.drop_constraint(None, 'lab_tests', type_='unique')
    op.drop_constraint(None, 'hospital', type_='unique')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_constraint(None, 'doctor_specialization', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_constraint(None, 'admissions', type_='unique')
    # ### end Alembic commands ###
